package throwing.predefined.exception.manually;

public class Test {

	public static void main(String[] args) {
		
		throw new ArithmeticException("/ by zero problem");

	}

}
